name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Clone the repo
      - uses: actions/checkout@v2

      # Initialise the ./bin directory
      - name: Initialisation 
        run: mkdir bin 

      # Download uow-util
      - name: Download uow-util
        id: download-uow-util
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: mbg/uow-apis
          tag: 'latest'
          path: bin
          file: uow-util
      
      # Publish the files from this repository to Sitebuilder
      - name: Publish to Sitebuilder 
        id: publish
        env: 
          UOW_USER: ${{ secrets.SB_USER }}
          UOW_PASSWORD: ${{ secrets.SB_PASSWORD }}
        run: |
          sudo chmod +x ./bin/uow-util
          ./bin/uow-util sitebuilder sync --config=sitebuilder.yaml

      - uses: iRoachie/slack-github-actions@v2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: always()
